security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        main_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: main_provider
            logout:
                        path: /logout
                        target: /